from __future__ import annotations

import json
from pathlib import Path

from aave.cli import main
from aave.genome import crossref_snp_hits, parse_ancestrydna_file


def write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def build_whitelist(path: Path) -> Path:
    write_json(
        path,
        [
            {
                "rsid": "rs123",
                "gene": "GENE1",
                "label": "Synthetic observed SNP",
                "category": "synthetic",
                "source_url": "https://www.snpedia.com/index.php/Rs123",
                "evidence_note": "Synthetic educational note.",
                "limitations": "Synthetic fixture only.",
                "public_summary_allowed": True,
            },
            {
                "rsid": "rs456",
                "gene": "GENE2",
                "label": "Synthetic missing SNP",
                "category": "synthetic",
                "source_url": "https://www.snpedia.com/index.php/Rs456",
                "evidence_note": "Synthetic educational note.",
                "limitations": "Missing means missing or not tested.",
                "public_summary_allowed": False,
            },
        ],
    )
    return path


def build_yaml_whitelist(path: Path) -> Path:
    path.write_text(
        "\n".join(
            [
                "- rsid: rs123",
                "  gene: GENE1",
                "  label: Synthetic observed SNP",
                "  category: synthetic",
                "  source_url: https://www.snpedia.com/index.php/Rs123",
                "  evidence_note: Synthetic educational note.",
                "  limitations: Synthetic fixture only.",
                "  public_summary_allowed: true",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return path


def build_ancestrydna_fixture(path: Path) -> Path:
    path.write_text(
        "\n".join(
            [
                "# Generated by synthetic test fixture",
                "# Reference build synthetic",
                "rsid chromosome position allele1 allele2",
                "rs123 1 100 A G",
                "rs123 1 100 A G",
                "rs789 2 200 C T",
                "malformed row",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return path


def test_parse_ancestrydna_writes_private_whitelist_outputs(tmp_path: Path) -> None:
    input_path = build_ancestrydna_fixture(tmp_path / "ancestrydna.txt")
    whitelist_path = build_whitelist(tmp_path / "genome-snp-list.json")
    output_directory = tmp_path / "genome_out"

    parse_result = parse_ancestrydna_file(input_path, whitelist_path, output_directory)

    manifest = json.loads((output_directory / "manifest.json").read_text())
    hits = json.loads((output_directory / "snp_hits.json").read_text())
    missing = json.loads((output_directory / "snp_missing.json").read_text())
    public_summary = json.loads((output_directory / "genome_public_summary.json").read_text())
    audit = (output_directory / "genome_audit.md").read_text()

    assert parse_result.rows_read == 3
    assert parse_result.hit_count == 1
    assert parse_result.missing_count == 1
    assert parse_result.malformed_row_count == 1
    assert parse_result.duplicate_rsid_count == 1
    assert manifest["raw_file_copied"] is False
    assert manifest["privacy_label"] == "raw_dna_never_export"
    assert hits[0]["rsid"] == "rs123"
    assert hits[0]["allele1"] == "A"
    assert hits[0]["allele2"] == "G"
    assert hits[0]["source_confidence"] == "private_artifact"
    assert missing[0]["status"] == "missing_or_not_tested"
    assert public_summary["raw_genotypes_included"] is False
    assert "allele1" not in public_summary
    assert "not medical, diagnostic, or health advice" in audit


def test_crossref_snp_hits_writes_annotated_private_output(tmp_path: Path) -> None:
    input_path = build_ancestrydna_fixture(tmp_path / "ancestrydna.txt")
    whitelist_path = build_whitelist(tmp_path / "genome-snp-list.json")
    parse_output_directory = tmp_path / "genome_out"
    parse_ancestrydna_file(input_path, whitelist_path, parse_output_directory)

    crossref_output_directory = tmp_path / "crossref_out"
    crossref_result = crossref_snp_hits(
        parse_output_directory / "snp_hits.json",
        whitelist_path,
        crossref_output_directory,
    )

    annotated_hits = json.loads(
        (crossref_output_directory / "snp_hits_annotated.json").read_text()
    )
    audit = (crossref_output_directory / "snp_crossref_audit.md").read_text()

    assert crossref_result.hit_count == 1
    assert crossref_result.annotated_count == 1
    assert annotated_hits[0]["gene"] == "GENE1"
    assert "Educational metadata only" in annotated_hits[0]["interpretation_scope"]
    assert "does not scrape SNPedia" in audit


def test_cli_genome_parse_and_crossref_commands(tmp_path: Path) -> None:
    input_path = build_ancestrydna_fixture(tmp_path / "ancestrydna.txt")
    whitelist_path = build_whitelist(tmp_path / "genome-snp-list.json")
    parse_output_directory = tmp_path / "genome_out"
    crossref_output_directory = tmp_path / "crossref_out"

    parse_exit_code = main(
        [
            "genome",
            "parse-ancestrydna",
            "--input",
            str(input_path),
            "--whitelist",
            str(whitelist_path),
            "--out",
            str(parse_output_directory),
        ]
    )
    crossref_exit_code = main(
        [
            "genome",
            "crossref",
            "--hits",
            str(parse_output_directory / "snp_hits.json"),
            "--whitelist",
            str(whitelist_path),
            "--out",
            str(crossref_output_directory),
        ]
    )

    assert parse_exit_code == 0
    assert crossref_exit_code == 0
    assert (parse_output_directory / "snp_hits.json").exists()
    assert (crossref_output_directory / "snp_hits_annotated.json").exists()


def test_parse_ancestrydna_accepts_yaml_snpedia_keys(tmp_path: Path) -> None:
    input_path = build_ancestrydna_fixture(tmp_path / "ancestrydna.txt")
    whitelist_path = build_yaml_whitelist(tmp_path / "snpedia_keys.yaml")
    output_directory = tmp_path / "genome_out"

    parse_result = parse_ancestrydna_file(input_path, whitelist_path, output_directory)
    hits = json.loads((output_directory / "snp_hits.json").read_text())

    assert parse_result.hit_count == 1
    assert hits[0]["source_url"] == "https://www.snpedia.com/index.php/Rs123"
    assert hits[0]["public_summary_allowed"] is True
